version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./backups:/home/backups
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha33
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      #HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/joe
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@192.168.99.100:5432/joe
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
volumes:
  db_data:
